#添加自定义代理组      
prepend-proxy-groups: 
  - name: 选择模式
    type: select
    proxies:
      - 强国
      # 只有命中规则的网络流量，才使用代理
      - 留学
      # 没有命中规则的网络流量，统统使用代理
  - name: All-PROXY
    type: select
    proxies:
      - JP
      - HK
      - TW
      - USA
    # Game
  - name: MapleStory
    type: select
    proxies:
      - JP
      - TW
      - USA
  - name: Elsword
    type: select
    proxies:
      - DIRECT
      - JP
    # Area
  - name: JP
    type: select
    proxies:
  - name: HK
    type: select
    proxies:
  - name: TW
    type: select
    proxies:
  - name: USA
    type: select
    proxies:
  - name: SEA
    type: select
    proxies:
  # Other
  - name: JP手游
    type: select
    proxies:
  - name: JP手游数据下载
    type: select
    proxies:
      - DIRECT
      - JP手游
  - name: Netflix
    type: select
    proxies:
      - JP
      - HK
      - TW
      - USA
  - name: Steam
    type: select
    proxies:
      - DIRECT
      - All-PROXY   
  # End
  - name: 强国
    type: select
    proxies:
      - DIRECT
  - name: 留学
    type: select
    proxies:
      - All-PROXY
  - name: ADBlock
    type: select
    proxies:
      - REJECT
commands:
#- proxy-groups.All-PROXY.proxies=[]proxyNames # 向指定策略组添加订阅中的节点名
  - proxy-groups.All-PROXY.proxies.0+DIRECT # 向指All-PROXY第一个位置添加DIRECT节点
  - proxy-groups.JP手游.proxies.0+JP
  - proxy-groups.JP手游.proxies.1+HK
  - proxy-groups.JP手游.proxies.2+TW
  - proxy-groups.JP.proxies=[]proxyNames|(日|JP)
  - proxy-groups.HK.proxies=[]proxyNames|(香|HK)
  - proxy-groups.TW.proxies=[]proxyNames|(台|TW)
  - proxy-groups.USA.proxies=[]proxyNames|(美|USA)
  - proxy-groups.SEA.proxies=[]proxyNames|(MY|SG|马来|新加坡)
#添加自定义规则
mix-rule-providers:
  #以下放置于 rule-providers，注意对齐
  ADBlock: # 广告域名列表
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/reject.txt"
    path: ./ruleset/reject.yaml
    interval: 86400
  MapleStory:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/leeharuhiofcn/LeeClash@main/rule-providers/MapleStory.yaml"
    path: ./ruleset/MapleStory.yaml
    interval: 86400
  Elsword:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/leeharuhiofcn/LeeClash@main/rule-providers/Elsword.yaml"
    path: ./ruleset/Elsword.yaml
    interval: 86400
  # JP severs
  JP: #Life-JP
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/leeharuhiofcn/LeeClash@main/rule-providers/Life-JP.yaml"
    path: ./ruleset/Life-JP.yaml
    interval: 86400
  JP: #Cygames-JP
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/leeharuhiofcn/LeeClash@main/rule-providers/Cygames-JP.yaml"
    path: ./ruleset/Cygames-JP.yaml
    interval: 86400
  JP: #Amazon
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/leeharuhiofcn/LeeClash@main/rule-providers/Amazon.yaml"
    path: ./ruleset/Amazon.yaml
    interval: 86400
  JP: #Games-JP
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/leeharuhiofcn/LeeClash@main/rule-providers/Games-JP.yaml"
    path: ./ruleset/Games-JP.yaml
    interval: 86400
  JP: #Elsword
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/leeharuhiofcn/LeeClash@main/rule-providers/Elsword.yaml"
    path: ./ruleset/Elsword.yaml
    interval: 86400

  Steam:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/leeharuhiofcn/LeeClash@main/rule-providers/Steam.yaml"
    path: ./ruleset/Steam.yaml
    interval: 86400
  # SNS
  留学:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/leeharuhiofcn/LeeClash@main/rule-providers/telegramcidr.yaml"
    path: ./ruleset/telegramcidr.yaml
    interval: 86400
  留学:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/leeharuhiofcn/LeeClash@main/rule-providers/Line.yaml"
    path: ./ruleset/Line.yaml
    interval: 86400
  留学:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/leeharuhiofcn/LeeClash@main/rule-providers/Discord.yaml"
    path: ./ruleset/Discord.yaml
    interval: 86400
  # 流媒体
  Netflix:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/leeharuhiofcn/LeeClash@main/rule-providers/Netflix.yaml"
    path: ./ruleset/Netflix.yaml
    interval: 86400
prepend-rules: 
# > Rule Set
# >建议使用DOMAIN-SUFFIX，而不是DOMAIN，很多时候你不知道你的使用的服务的域名结构
# > DIRECT of China
  - DOMAIN-KEYWORD,agefans,DIRECT
  - DOMAIN-KEYWORD,nga.178.com,DIRECT
  - DOMAIN-KEYWORD,dogess,留学
# > www.dmhy.org
  - DOMAIN-SUFFIX,dmhy.org,All-PROXY  
  - DOMAIN-SUFFIX,instructables.com,All-PROXY
# > other
  - DOMAIN-SUFFIX,cn,DIRECT
  - DOMAIN-KEYWORD,-cn,DIRECT
  - DOMAIN,p-bstarstatic.akamaized.net,强国
  - DOMAIN,p.bstarstatic.com,强国
  - DOMAIN,upos-bstar-mirrorakam.akamaized.net,强国
  - DOMAIN,upos-bstar1-mirrorakam.akamaized.net,强国
  - DOMAIN,upos-hz-mirrorakam.akamaized.net,强国
  - DOMAIN-SUFFIX,acgvideo.com,强国
  - DOMAIN-SUFFIX,bilibili.com,强国
  - DOMAIN-SUFFIX,bilibili.tv,强国
  - IP-CIDR,45.43.32.234/32,强国
  - IP-CIDR,119.29.29.29/32,强国
  - IP-CIDR,128.1.62.200/32,强国
  - IP-CIDR,128.1.62.201/32,强国
  - IP-CIDR,150.116.92.250/32,强国
  - IP-CIDR,164.52.76.18/32,强国
  - IP-CIDR,203.107.1.33/32,强国
  - IP-CIDR,203.107.1.34/32,强国
  - IP-CIDR,203.107.1.65/32,强国
  - IP-CIDR,203.107.1.66/32,强国
  - DOMAIN,apiintl.biliapi.net,强国
  - DOMAIN,upos-hz-mirrorakam.akamaized.net,强国
  - DOMAIN-SUFFIX,acg.tv,强国
  - DOMAIN-SUFFIX,acgvideo.com,强国
  - DOMAIN-SUFFIX,b23.tv,强国
  - DOMAIN-SUFFIX,bigfun.cn,强国
  - DOMAIN-SUFFIX,bigfunapp.cn,强国
  - DOMAIN-SUFFIX,biliapi.com,强国
  - DOMAIN-SUFFIX,biliapi.net,强国
  - DOMAIN-SUFFIX,bilibili.com,强国
  - DOMAIN-SUFFIX,bilibili.tv,强国
  - DOMAIN-SUFFIX,biligame.com,强国
  - DOMAIN-SUFFIX,biligame.net,强国
  - DOMAIN-SUFFIX,bilivideo.cn,强国
  - DOMAIN-SUFFIX,bilivideo.com,强国
  - DOMAIN-SUFFIX,hdslb.com,强国
  - DOMAIN-SUFFIX,im9.com,强国
  - DOMAIN-SUFFIX,smtcdns.net,强国
  - PROCESS-NAME,v2ray,强国
  - PROCESS-NAME,xray,强国
  - PROCESS-NAME,naive,强国
  - PROCESS-NAME,trojan,强国
  - PROCESS-NAME,trojan-go,强国
  - PROCESS-NAME,ss-local,强国
  - PROCESS-NAME,privoxy,强国
  - PROCESS-NAME,leaf,强国
  - PROCESS-NAME,v2ray.exe,强国
  - PROCESS-NAME,xray.exe,强国
  - PROCESS-NAME,naive.exe,强国
  - PROCESS-NAME,trojan.exe,强国
  - PROCESS-NAME,trojan-go.exe,强国
  - PROCESS-NAME,ss-local.exe,强国
  - PROCESS-NAME,privoxy.exe,强国
  - PROCESS-NAME,leaf.exe,强国
  - PROCESS-NAME,Surge,强国
  - PROCESS-NAME,Surge 2,强国
  - PROCESS-NAME,Surge 3,强国
  - PROCESS-NAME,Surge 4,强国
  - PROCESS-NAME,Surge%202,强国
  - PROCESS-NAME,Surge%203,强国
  - PROCESS-NAME,Surge%204,强国
  - PROCESS-NAME,Thunder,强国
  - PROCESS-NAME,DownloadService,强国
  - PROCESS-NAME,qBittorrent,强国
  - PROCESS-NAME,Transmission,强国
  - PROCESS-NAME,fdm,强国
  - PROCESS-NAME,aria2c,强国
  - PROCESS-NAME,Folx,强国
  - PROCESS-NAME,NetTransport,强国
  - PROCESS-NAME,uTorrent,强国
  - PROCESS-NAME,WebTorrent,强国
  - PROCESS-NAME,aria2c.exe,强国
  - PROCESS-NAME,BitComet.exe,强国
  - PROCESS-NAME,fdm.exe,强国
  - PROCESS-NAME,NetTransport.exe,强国
  - PROCESS-NAME,qbittorrent.exe,强国
  - PROCESS-NAME,Thunder.exe,强国
  - PROCESS-NAME,ThunderVIP.exe,强国
  - PROCESS-NAME,transmission-daemon.exe,强国
  - PROCESS-NAME,transmission-qt.exe,强国
  - PROCESS-NAME,uTorrent.exe,强国
  - PROCESS-NAME,WebTorrent.exe,强国
  - GEOIP,CN,强国
  - MATCH,选择模式
