#添加自定义代理组      
prepend-proxy-groups: 
  - name: 选择模式
    type: select
    proxies:
      - 强国
      # 只有命中规则的网络流量，才使用代理
      - 留学
      # 没有命中规则的网络流量，统统使用代理
  - name: All-PROXY
    type: select
    proxies:
      - JP
      - HK
      - TW
      - USA
    # Game
  - name: MapleStory
    type: select
    proxies:
      - JP
      - TW
      - USA
  - name: Elsword
    type: select
    proxies:
      - DIRECT
      - JP
    # Area
  - name: JP
    type: select
    proxies:
  - name: HK
    type: select
    proxies:
  - name: TW
    type: select
    proxies:
  - name: USA
    type: select
    proxies:
  - name: SEA
    type: select
    proxies:
  # Other
  - name: JP手游
    type: select
    proxies:
  - name: JP手游数据下载
    type: select
    proxies:
      - DIRECT
      - JP手游
  - name: Netflix
    type: select
    proxies:
      - JP
      - HK
      - TW
      - USA
  - name: Steam
    type: select
    proxies:
      - DIRECT
      - All-PROXY   
  # End
  - name: 强国
    type: select
    proxies:
      - DIRECT
  - name: 留学
    type: select
    proxies:
      - All-PROXY
  - name: ADBlock
    type: select
    proxies:
      - REJECT
commands:
#- proxy-groups.All-PROXY.proxies=[]proxyNames # 向指定策略组添加订阅中的节点名
  - proxy-groups.All-PROXY.proxies.0+DIRECT # 向指All-PROXY第一个位置添加DIRECT节点
  - proxy-groups.JP手游.proxies.0+JP
  - proxy-groups.JP手游.proxies.1+HK
  - proxy-groups.JP手游.proxies.2+TW
  - proxy-groups.JP.proxies=[]proxyNames|(日|JP)
  - proxy-groups.HK.proxies=[]proxyNames|(香|HK)
  - proxy-groups.TW.proxies=[]proxyNames|(台|TW)
  - proxy-groups.USA.proxies=[]proxyNames|(美|USA)
  - proxy-groups.SEA.proxies=[]proxyNames|(MY|SG|马来|新加坡)
#添加自定义规则
prepend-rules: 
# > Rule Set
# >建议使用DOMAIN-SUFFIX，而不是DOMAIN，很多时候你不知道你的使用的服务的域名结构
# > DIRECT of China
  - RULE-SET,MapleStory,MapleStory
  - RULE-SET,Elsword,Elsword
  - RULE-SET,Life-JP,JP
  - RULE-SET,Cygames-JP,JP
  - RULE-SET,Amazon,JP  
  - RULE-SET,Games-JP,JP
  - RULE-SET,Steam,Steam
  - RULE-SET,telegramcidr,留学
  - RULE-SET,Line,留学
  - RULE-SET,Discord,留学
  - RULE-SET,Netflix,Netflix
  - RULE-SET,ADBlocl,ADBlock
  - GEOIP,CN,强国
  - MATCH,选择模式
mix-rule-providers:
  #以下放置于 rule-providers，注意对齐
#以下放置于 rule-providers，注意对齐
  ADBlock: # 广告域名列表
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/reject.txt"
    path: ./ruleset/reject.yaml
    interval: 86400
  MapleStory:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/leeharuhiofcn/LeeClash@main/rule-providers/MapleStory.yaml"
    path: ./ruleset/MapleStory.yaml
    interval: 86400

  Elsword: 
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/leeharuhiofcn/LeeClash@main/rule-providers/Elsword.yaml"
    path: ./ruleset/Elsword.yaml
    interval: 86400
  # JP severs
  Life-JP: 
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/leeharuhiofcn/LeeClash@main/rule-providers/Life-JP.yaml"
    path: ./ruleset/Life-JP.yaml
    interval: 86400
  Cygames-JP: 
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/leeharuhiofcn/LeeClash@main/rule-providers/Cygames-JP.yaml"
    path: ./ruleset/Cygames-JP.yaml
    interval: 86400
  Amazon:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/leeharuhiofcn/LeeClash@main/rule-providers/Amazon.yaml"
    path: ./ruleset/Amazon.yaml
    interval: 86400
  Games-JP:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/leeharuhiofcn/LeeClash@main/rule-providers/Games-JP.yaml"
    path: ./ruleset/Games-JP.yaml
    interval: 86400
  Steam:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/leeharuhiofcn/LeeClash@main/rule-providers/Steam.yaml"
    path: ./ruleset/Steam.yaml
    interval: 86400
  # SNS
  telegramcidr:
    type: http
    behavior: ipcidr
    url: "https://cdn.jsdelivr.net/gh/leeharuhiofcn/LeeClash@main/rule-providers/telegramcidr.yaml"
    path: ./ruleset/telegramcidr.yaml
    interval: 86400
  Line:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/leeharuhiofcn/LeeClash@main/rule-providers/Line.yaml"
    path: ./ruleset/Line.yaml
    interval: 86400
  Discord:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/leeharuhiofcn/LeeClash@main/rule-providers/Discord.yaml"
    path: ./ruleset/Discord.yaml
    interval: 86400
  # 流媒体
  Netflix:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/leeharuhiofcn/LeeClash@main/rule-providers/Netflix.yaml"
    path: ./ruleset/Netflix.yaml
    interval: 86400